apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
    traefik.constraint-label: traefik-public
    traefik.docker.network: traefik-public
    traefik.enable: "true"
    traefik.http.routers.full-stack-fastapi-project-frontend-http.entrypoints: http
    traefik.http.routers.full-stack-fastapi-project-frontend-http.middlewares: https-redirect,full-stack-fastapi-project-www-redirect
    traefik.http.routers.full-stack-fastapi-project-frontend-http.rule: Host(`localhost`, `www.localhost`)
    traefik.http.routers.full-stack-fastapi-project-frontend-https.entrypoints: https
    traefik.http.routers.full-stack-fastapi-project-frontend-https.middlewares: full-stack-fastapi-project-www-redirect
    traefik.http.routers.full-stack-fastapi-project-frontend-https.rule: Host(`localhost`, `www.localhost`)
    traefik.http.routers.full-stack-fastapi-project-frontend-https.tls: "true"
    traefik.http.routers.full-stack-fastapi-project-frontend-https.tls.certresolver: le
    traefik.http.services.full-stack-fastapi-project-frontend.loadbalancer.server.port: "80"
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: "true"
        traefik.http.routers.full-stack-fastapi-project-frontend-http.entrypoints: http
        traefik.http.routers.full-stack-fastapi-project-frontend-http.middlewares: https-redirect,full-stack-fastapi-project-www-redirect
        traefik.http.routers.full-stack-fastapi-project-frontend-http.rule: Host(`localhost`, `www.localhost`)
        traefik.http.routers.full-stack-fastapi-project-frontend-https.entrypoints: https
        traefik.http.routers.full-stack-fastapi-project-frontend-https.middlewares: full-stack-fastapi-project-www-redirect
        traefik.http.routers.full-stack-fastapi-project-frontend-https.rule: Host(`localhost`, `www.localhost`)
        traefik.http.routers.full-stack-fastapi-project-frontend-https.tls: "true"
        traefik.http.routers.full-stack-fastapi-project-frontend-https.tls.certresolver: le
        traefik.http.services.full-stack-fastapi-project-frontend.loadbalancer.server.port: "80"
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: frontend:latest
          name: frontend
      restartPolicy: Always
